---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: approved-caddy
spec:
  importPolicy:
    scheduled: true
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: docker.io/caddy:2-alpine
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: caddy-reverse-proxy
